# Generated by Django 2.2.4 on 2019-10-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('flavor', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('flavor', models.TextField(blank=True, default=None)),
                ('loop', models.BooleanField(default=False)),
                ('sound_file', models.FileField(upload_to='music/')),
                ('tags', models.ManyToManyField(blank=True, to='api.Tag')),
            ],
        ),
    ]
