# Generated by Django 2.2.4 on 2019-10-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_npc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='description',
        ),
        migrations.AddField(
            model_name='npc',
            name='appearance',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='npc',
            name='lore',
            field=models.TextField(blank=True, default=None),
        ),
    ]
