# Generated by Django 2.2.6 on 2019-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191018_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='met',
            new_name='hidden',
        ),
        migrations.AddField(
            model_name='song',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
