# Generated by Django 2.2.6 on 2019-10-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191030_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lore',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='lore',
        ),
        migrations.AddField(
            model_name='city',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='npc',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='npc',
            name='appearance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='npc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.City'),
        ),
        migrations.AlterField(
            model_name='song',
            name='flavor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='flavor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('aliases', models.TextField(blank=True, default='')),
                ('visible', models.BooleanField(default=False)),
                ('lore_type', models.CharField(choices=[('Book', 'Book'), ('General', 'General'), ('Letter', 'Letter')], max_length=32)),
                ('date_received', models.DateField(blank=True, default=None)),
                ('date_written', models.DateField(blank=True, default=None)),
                ('text', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.NPC')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
