# Generated by Django 2.2.6 on 2019-11-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191105_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_file',
            field=models.FileField(blank=True, upload_to='cities/'),
        ),
    ]
