# Generated by Django 2.2.6 on 2019-11-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_city_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('aliases', models.TextField(blank=True, default='')),
                ('visible', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('info', models.TextField(blank=True, default='')),
                ('image_file', models.FileField(blank=True, upload_to='places/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='npc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Place'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
