# Generated by Django 2.2.7 on 2019-11-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_place_points_of_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_type',
            new_name='type',
        ),
    ]
