# Generated by Django 2.2.7 on 2019-11-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191110_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
