# Generated by Django 2.2.7 on 2019-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191110_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='date_received',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lore',
            name='date_written',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
