# Generated by Django 2.2.7 on 2019-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191110_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='lore_type',
            field=models.CharField(choices=[('Book', 'Book'), ('General', 'General'), ('Letter', 'Letter'), ('Story', 'Story')], max_length=32),
        ),
    ]
