# Generated by Django 2.2.7 on 2019-11-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191110_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lore',
            old_name='lore_type',
            new_name='type',
        ),
    ]
