# Generated by Django 2.2.7 on 2019-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_monsters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('aliases', models.TextField(blank=True, default='')),
                ('visible', models.BooleanField(default=False)),
                ('appearance', models.TextField(blank=True, default='')),
                ('info', models.TextField(blank=True, default='')),
                ('image_file', models.FileField(blank=True, upload_to='beasts/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Monsters',
        ),
    ]
