# Generated by Django 2.2.7 on 2019-11-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191110_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beasts',
            new_name='Beast',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
