# Generated by Django 2.2.7 on 2019-11-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ordinal',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
