# Generated by Django 2.2.1 on 2019-07-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.TextField()),
                ('tags', models.CharField(max_length=64)),
                ('loop', models.BooleanField(default=False)),
                ('sound_file', models.FileField(upload_to='uploads/music/')),
            ],
        ),
    ]
