# Generated by Django 2.2.1 on 2019-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('flavor', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='flavor',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='panel.SongTag'),
        ),
    ]
