# Generated by Django 2.2.1 on 2019-07-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20190724_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sound_file',
            field=models.FileField(upload_to='music/'),
        ),
    ]
