# Generated by Django 2.2.3 on 2019-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_letter_lore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.TextField(blank=True, default=None)),
                ('image_file', models.FileField(upload_to='images/')),
            ],
        ),
    ]
