# Generated by Django 2.2.1 on 2019-08-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongTag',
            new_name='Tag',
        ),
    ]
