# Generated by Django 2.2.4 on 2019-08-27 19:32

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('panel', '0007_campaign_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='images',
        ),
        migrations.RemoveField(
            model_name='session',
            name='letters',
        ),
        migrations.RemoveField(
            model_name='session',
            name='lores',
        ),
        migrations.RemoveField(
            model_name='session',
            name='songs',
        ),
        migrations.AddField(
            model_name='session',
            name='data_items',
            field=gm2m.fields.GM2MField(through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
