# Generated by Django 2.2.4 on 2019-08-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('panel', '0008_auto_20190827_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='data_items',
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Session')),
            ],
        ),
    ]
