# Generated by Django 2.2.4 on 2019-08-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20190828_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.TextField(blank=True, default=None)),
                ('image_file', models.FileField(blank=True, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sessionitem',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='CityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default=None)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.City')),
            ],
        ),
    ]
