# Generated by Django 2.2.4 on 2019-08-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20190831_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
