# Generated by Django 2.2.4 on 2019-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_cityitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityitem',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
