# Generated by Django 2.2.4 on 2019-09-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.TextField(blank=True, default=None)),
                ('image_file', models.FileField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DungeonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('text', models.TextField(blank=True, default=None)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Dungeon')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
