# Generated by Django 2.2.4 on 2019-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_dungeon_dungeonitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.TextField(blank=True, default=None)),
                ('image_file', models.FileField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
